# Generated by Django 4.1.3 on 2022-11-26 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('discipline_id', models.AutoField(db_column='discipline_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('priority', models.IntegerField(db_column='priority', default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(db_column='type_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('priority', models.IntegerField(db_column='priority', default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(db_column='task_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('done', models.BooleanField(db_column='done', default=False)),
                ('datetime', models.DateTimeField(db_column='datetime', null=True)),
                ('discipline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizer.discipline')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizer.type')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
